//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Code\you\Qik\Code\Current\QikAntlr\QikTemplate.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CygSoft.Qik.Antlr {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IQikTemplateListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class QikTemplateBaseListener : IQikTemplateListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.template"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplate([NotNull] QikTemplateParser.TemplateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.template"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplate([NotNull] QikTemplateParser.TemplateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.ctrlDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCtrlDecl([NotNull] QikTemplateParser.CtrlDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.ctrlDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCtrlDecl([NotNull] QikTemplateParser.CtrlDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.optionBox"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionBox([NotNull] QikTemplateParser.OptionBoxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.optionBox"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionBox([NotNull] QikTemplateParser.OptionBoxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.textBox"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTextBox([NotNull] QikTemplateParser.TextBoxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.textBox"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTextBox([NotNull] QikTemplateParser.TextBoxContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.optionsBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionsBody([NotNull] QikTemplateParser.OptionsBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.optionsBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionsBody([NotNull] QikTemplateParser.OptionsBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.singleOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleOption([NotNull] QikTemplateParser.SingleOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.singleOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleOption([NotNull] QikTemplateParser.SingleOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.exprDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprDecl([NotNull] QikTemplateParser.ExprDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.exprDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprDecl([NotNull] QikTemplateParser.ExprDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.optExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptExpr([NotNull] QikTemplateParser.OptExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.optExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptExpr([NotNull] QikTemplateParser.OptExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.ifOptExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfOptExpr([NotNull] QikTemplateParser.IfOptExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.ifOptExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfOptExpr([NotNull] QikTemplateParser.IfOptExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.declArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclArgs([NotNull] QikTemplateParser.DeclArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.declArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclArgs([NotNull] QikTemplateParser.DeclArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.declArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclArg([NotNull] QikTemplateParser.DeclArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.declArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclArg([NotNull] QikTemplateParser.DeclArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] QikTemplateParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] QikTemplateParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.concatExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConcatExpr([NotNull] QikTemplateParser.ConcatExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.concatExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConcatExpr([NotNull] QikTemplateParser.ConcatExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc([NotNull] QikTemplateParser.FuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc([NotNull] QikTemplateParser.FuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QikTemplateParser.funcArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncArg([NotNull] QikTemplateParser.FuncArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QikTemplateParser.funcArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncArg([NotNull] QikTemplateParser.FuncArgContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace CygSoft.Qik.Antlr
