//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Code\you\Qik\Code\Current\QikAntlr\QikTemplate.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CygSoft.Qik.Antlr {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="QikTemplateParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IQikTemplateVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplate([NotNull] QikTemplateParser.TemplateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.ctrlDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtrlDecl([NotNull] QikTemplateParser.CtrlDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.optionBox"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionBox([NotNull] QikTemplateParser.OptionBoxContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.textBox"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTextBox([NotNull] QikTemplateParser.TextBoxContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.optionsBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionsBody([NotNull] QikTemplateParser.OptionsBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.singleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleOption([NotNull] QikTemplateParser.SingleOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.exprDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprDecl([NotNull] QikTemplateParser.ExprDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.optExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptExpr([NotNull] QikTemplateParser.OptExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.ifOptExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfOptExpr([NotNull] QikTemplateParser.IfOptExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.declArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclArgs([NotNull] QikTemplateParser.DeclArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.declArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclArg([NotNull] QikTemplateParser.DeclArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] QikTemplateParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.concatExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcatExpr([NotNull] QikTemplateParser.ConcatExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc([NotNull] QikTemplateParser.FuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="QikTemplateParser.funcArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncArg([NotNull] QikTemplateParser.FuncArgContext context);
}
} // namespace CygSoft.Qik.Antlr
